apiVersion: v1
kind: Pod
metadata:
  name: Postgres
  labels:
    name: Postgres
    app: demo-voting-app
spec:
  containers:
  - name: Postgres
    image: postgres:9.4
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5432
