apiVersion: v1
kind: POD
metadata:
  name:  redis
  labels:
    name:  redis
    app:  demo-voting-app
spec:
  containers:
    - name: redis
      image:  redis
      ports:
      - containerPort: 6379