apiVersion: v1
kind: POD
metadata:
  name: result-app
  labels:
    name: result-app
    app: demo-voting-app
spec:
  containers:
    - name:  result-app
      image:  dockersamples/examplevotingapp_result
      resources:
        limits:
          memory: "128mi"
          cpu: "500m"
      ports:
      - containerPort: 80
    
